[package]
name = "ace"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.11.0"
derive_more = "2.0.1"
env_logger = "0.11.8"
log = "0.4.27"
serde = "1.0.219"
strum = "0.27.2"
strum_macros = "0.27.2"
uuid = "1.17.0"

