name: Rust CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://postgres:password@localhost:5432/testdb

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install SQLx CLI (optional)
        run: cargo install sqlx-cli --no-default-features --features postgres

      - name: Install project dependencies
        run: cargo fetch

      - name: Build project
        run: cargo build --verbose

      - name: Run DB Migrations
        run: sqlx migrate run

      - name: Run tests
        run: cargo test --all
